behaviors:
  ArcherBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 10240
      learning_rate: 1.0e-3
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 0
    summary_freq: 1000
    threaded: true

environment_parameters:
  xpos:
    sampler_type: uniform
    sampler_parameters:
        min_value: -10
        max_value: 10

  windMag:
    sampler_type: gaussian
    sampler_parameters:
        mean: 6
        st_dev: 3

  windDir:
    sampler_type: uniform
    sampler_parameters:
        min_value: 0
        max_value: 6.28
